---
title: "transcriptomics_plots"
author: "Degnan, David J"
date: "2023-04-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, error = FALSE)
library(data.table)
library(plotly)
```

## Read data 

```{r}
transcriptomics <- fread("~/Downloads/transcriptomics_out.txt")
```

## Chemical Page Level

#### Counts of Significant Genes per Concentration

```{r}
# As an example, pull chemical
ChemicalID <- "50-32-8"

# Data at the chemical level
chem_level <- transcriptomics[transcriptomics$CASNO == ChemicalID,]

chem_level %>%
  filter(adj_p_value <= 0.05) %>%
  count(Concentration) %>%
  mutate(Concentration = as.factor(Concentration)) %>%
  plot_ly(x = ~Concentration, 
          color = ~Concentration,
          y = ~n,
          type = "bar") %>%
  layout(yaxis = list(title = "Number of Significant Genes"),
         xaxis = list(title = "Concentration in uM"))
```

#### Expression of significant genes 

```{r}
chem_level %>%
  filter(adj_p_value <= 0.05) 




```


