ENDPOINTS = [
    "AXIS",
    "BRN_",
    "CRAN",
    "DNC_",
    "DP24",
    "EDEM",
    "LTRK",
    "MO24",
    "MORT",
    "MUSC",
    "NC__",
    "SKIN",
    "SM24",
    "TCHR",
]

brain_endpoints = [
    "BRAI",
    "CFIN",
    "CIRC",
    "DNC_",
    "EYE_",
    "JAW_",
    "NC24",
    "OTIC",
    "PE__",
    "PFIN",
    "PIG_",
    "SNOU",
    "SOMI",
    "SWIM",
    "TRUN",
    "TR__",
    "YSE_",
]

BRAIN_ENDPOINTS = sorted(ENDPOINTS + brain_endpoints)

CALC_ENDPOINTS = [
    "ANY24",
    "ANY120",
    "TOT_MORT",
    "ALL_BUT_MORT",
    "BRN_",
    "CRAN",
    "EDEM",
    "LTRK",
    "MUSC",
    "SKIN",
    "TCHR",
]

BRAIN_ENDPOINT_DICT = {
    "ANY24": ["MO24", "DP24", "SM24", "NC24"],
    "ANY120": [
        "MORT",
        "YSE_",
        "AXIS",
        "EYE_",
        "SNOU",
        "JAW_",
        "OTIC",
        "PE__",
        "BRAI",
        "SOMI",
        "PFIN",
        "CFIN",
        "PIG_",
        "CIRC",
        "TRUN",
        "SWIM",
        "NC__",
        "TR__",
        "ANY24",
    ],
    "TOT_MORT": ["MO24", "MORT"],
    "ALL_BUT_MORT": [
        "DP24",
        "SM24",
        "NC24",
        "YSE_",
        "AXIS",
        "EYE_",
        "SNOU",
        "JAW_",
        "OTIC",
        "PE__",
        "BRAI",
        "SOMI",
        "PFIN",
        "CFIN",
        "PIG_",
        "CIRC",
        "TRUN",
        "SWIM",
        "NC__",
        "TR__",
    ],
    "BRN_": ["BRAI", "OTIC", "PFIN"],
    "CRAN": ["EYE_", "SNOU", "JAW_"],
    "EDEM": ["YSE_", "PE__"],
    "LTRK": ["TRUN", "CFIN"],
    "MUSC": ["CIRC", "SWIM", "SOMI"],
    "SKIN": ["PIG_"],
    "TCHR": ["TR__"],
}

ENDPOINT_DICT = {
    "ANY24": ["MO24", "DP24", "SM24"],
    "ANY120": [
        "AXIS",
        "BRN_",
        "CRAN",
        "EDEM",
        "LTRK",
        "MORT",
        "MUSC",
        "NC__",
        "SKIN",
        "TCHR",
        "ANY24",
    ],
    "TOT_MORT": ["MO24", "MORT"],
    "ALL_BUT_MORT": [
        "AXIS",
        "BRN_",
        "CRAN",
        "DP24",
        "EDEM",
        "LTRK",
        "MUSC",
        "NC__",
        "SKIN",
        "SM24",
        "TCHR",
    ],
}
