name: Build-upload-docker
defaults:
  run:
    working-directory: ./
on:
  push:
    branches:
      - '**'
    paths:
      - build_script.py
      - .github/
      - zfBmd/
      - zfExp/
      - sampleChemMapping/
      - dbSchema/
      - exposome/
  workflow_dispatch:


jobs:
  build-and-push-sample:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push sampleChem
        uses: docker/build-push-action@v3
        with:
         file: sampleChemMapping/Dockerfile
         tags: sgosline/srp-samplechem:latest
         platforms: linux/amd64,linux/arm64
         push: true
       
  build-push-expo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx     
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push expo
        uses: docker/build-push-action@v3
        with:
         file: exposome/Dockerfile
         platforms: linux/amd64,linux/arm64
         tags: sgosline/srp-exposome:latest
         push: true

  build-push-exp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3     
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push expr
        uses: docker/build-push-action@v3
        with:
         file: zfExp/Dockerfile
         push: true
         platforms: linux/amd64,linux/arm64
         tags: sgosline/srp-zfexp
#      - name: Build and push bmd
#        uses: docker/build-push-action@v6
#        with:
#          context: zfBmd
#          push: true
#          tags: sgosline/srp-zfbmd:latest
#          platforms: linux/amd64,linux/arm64       
#      - name: Build and push bmd2Samps
#        uses: docker/build-push-action@v6
#        with:
#          context: old/bmd2Samps
#          push: true
#          tags: sgosline/srp-bmd2samps:v1
#          platforms: linux/amd64,linux/arm64       
#      - name: Build and push version 2 bmd2Samps
#        uses: docker/build-push-action@v6
#        with:
#          context: old/bmd2Samps_v2
#          push: true
#          tags: sgosline/srp-bmd2samps:latest
#          platforms: linux/amd64,linux/arm64
